# Generated by Django 5.0.3 on 2024-04-21 11:43

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره تماس')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نام')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='اخرین ورود')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر مورد نظر ادمین است؟')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کاربر مورد نظر کارمند است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='کاربر مورد نظر فعال است؟')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='کاربر مورد نظر سوپرادمین است؟')),
                ('groups', models.ManyToManyField(blank=True, help_text='\n            گروه هایی که این کاربر به آنها تعلق دارد.\n            یک کاربر تمام مجوزهای اعطا\n            شده به هر یک از گروه های خود را دریافت می کند.\n            ', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='ادرس')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='کشور')),
                ('check_in', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out', models.DateField(verbose_name='تاریخ خروج')),
                ('guests_number', models.PositiveIntegerField(verbose_name='تعداد مهمان\u200cها')),
                ('national_code', models.IntegerField(unique=True, verbose_name='کد ملی')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='امتیازات وفاداری')),
                ('preferences', models.TextField(blank=True, verbose_name='ترجیحات اتاق')),
                ('satisfaction_level', models.IntegerField(blank=True, choices=[(1, 'بسیار ناراضی'), (2, 'ناراضی'), (3, 'معمولی'), (4, 'راضی'), (5, 'بسیار راضی')], null=True, verbose_name='میزان رضایت')),
                ('reservation_status', models.CharField(choices=[('reserved', 'رزرو شده'), ('checked_in', 'وارد شده'), ('checked_out', 'خارج شده'), ('cancelled', 'لغو شده')], max_length=50, verbose_name='وضعیت رزرو')),
                ('payment_status', models.CharField(choices=[('PAID', 'پرداخت شده'), ('PENDING', 'در انتظار'), ('FAILED', 'ناموفق')], max_length=10, verbose_name='وضعیت پرداخت')),
                ('room_number', models.CharField(blank=True, max_length=10, verbose_name='شماره اتاق')),
                ('special_requests', models.TextField(blank=True)),
                ('vip_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
        migrations.CreateModel(
            name='HotelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='بخش')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به کار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'permissions': (('can_manage_staff', 'می\u200cتواند کارکنان را مدیریت کند'), ('can_change_hotel_settings', 'می\u200cتواند تنظیمات هتل را تغییر دهد'), ('can_view_financial_reports', 'می\u200cتواند گزارش\u200cهای مالی را مشاهده کند')),
            },
        ),
        migrations.CreateModel(
            name='HotelStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('role', models.CharField(max_length=50, verbose_name='وظیفه')),
                ('working_hours', models.IntegerField(verbose_name='ساعات کاری')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به کار')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='بخش')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='تماس اضطراری')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حقوق')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'permissions': (('can_view', 'می\u200cتواند مشاهده کند'), ('can_edit', 'می\u200cتواند ویرایش کند'), ('can_delete', 'می\u200cتواند حذف کند')),
            },
        ),
    ]
