# Generated by Django 5.0.3 on 2024-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladmin',
            name='advanced_training_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل دوره\u200cهای آموزشی پیشرفته'),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='can_approve_transactions',
            field=models.BooleanField(default=False, verbose_name='تایید تراکنش\u200cها'),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='can_handle_complaints',
            field=models.BooleanField(default=False, verbose_name='رسیدگی به شکایات'),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='can_modify_policies',
            field=models.BooleanField(default=False, verbose_name='تغییر خط\u200cمشی\u200cها'),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='permissions_level',
            field=models.CharField(default='Full', max_length=50, verbose_name='سطح دسترسی'),
        ),
    ]
