# Generated by Django 5.0.3 on 2024-04-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hoteladmin_advanced_training_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteladmin',
            options={'permissions': (('can_manage_staff', 'می\u200cتواند کارکنان را مدیریت کند'), ('can_change_hotel_settings', 'می\u200cتواند تنظیمات هتل را تغییر دهد'), ('can_view_financial_reports', 'می\u200cتواند گزارش\u200cهای مالی را مشاهده کند')), 'verbose_name': 'مدیر هتل', 'verbose_name_plural': 'مدیران هتل'},
        ),
        migrations.AlterModelOptions(
            name='hotelstaff',
            options={'permissions': (('can_view', 'می\u200cتواند مشاهده کند'), ('can_edit', 'می\u200cتواند ویرایش کند'), ('can_delete', 'می\u200cتواند حذف کند')), 'verbose_name': 'کارمند هتل', 'verbose_name_plural': 'کارمندان هتل'},
        ),
    ]
